name: Compilar APK Android

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kivy/buildozer:latest

    steps:
    - name: Descargar codigo del repositorio
      uses: actions/checkout@v4

    - name: Compilar APK
      run: |
        buildozer init
        sed -i 's/android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
        buildozer -v android debug

    - name: Subir APK generado
      uses: actions/upload-artifact@v4
      with:
        name: App-Android-APK
        path: bin/*.apk
